CREATE TABLE vendas (
  "Rec No" INT,
  "Iditensvnd" INT,
  "Lkvenda" INT,
  "Lkvendedor" INT,
  "Lkcodprod" VARCHAR(255),
  "Sequenciaitemecf" INT,
  "Qtde" DECIMAL(10,3),
  "Valorunitario" DECIMAL(10,2),
  "Perdesconto" DECIMAL(5,2),
  "Desconto" DECIMAL(10,2),
  "Total" DECIMAL(10,2),
  "Percomissao" DECIMAL(5,2),
  "Comissao" DECIMAL(10,2),
  "Substituicao" VARCHAR(3),
  "Aliqicms" DECIMAL(5,2),
  "Valoricms" DECIMAL(10,2),
  "Valoripi" DECIMAL(10,2),
  "Valoriss" DECIMAL(10,2),
  "Custounitario" DECIMAL(10,2),
  "Qtdcancelada" DECIMAL(10,3),
  "Valorcancelado" DECIMAL(10,2),
  "Qtdaentregar" DECIMAL(10,3),
  "Vlrbruto" DECIMAL(10,2),
  "Datacancelamento" DATE,
  "Ippt Paf" VARCHAR(255),
  "Casasdecimaisquantidade" INT,
  "Casasdecimaisvalorunitario" INT,
  "Codigototalizadorparcial" VARCHAR(255),
  "Lote" VARCHAR(255),
  "Lklote" VARCHAR(255),
  "Autoprevsaude" INT,
  "Descespecial" INT,
  "Turno" INT
);