CREATE TABLE item_venda (
  "Rec No" INT PRIMARY KEY,
  "Iditensvnd" INT,
  "Lkvenda" INT,
  "Lkvendedor" INT,
  "Lkcodprod" VARCHAR(255),
  "Sequenciaitemecf" INT,
  "Qtde" DECIMAL,
  "Valorunitario" DECIMAL,
  "Perdesconto" DECIMAL,
  "Desconto" DECIMAL,
  "Total" DECIMAL,
  "Percomissao" DECIMAL,
  "Comissao" DECIMAL,
  "Substituicao" VARCHAR(3),
  "Aliqicms" DECIMAL,
  "Valoricms" DECIMAL,
  "Valoripi" DECIMAL,
  "Valoriss" DECIMAL,
  "Custounitario" DECIMAL,
  "Qtdcancelada" DECIMAL,
  "Valorcancelado" DECIMAL,
  "Qtdaentregar" DECIMAL,
  "Vlrbruto" DECIMAL,
  "Datacancelamento" DATE,
  "Ippt Paf" VARCHAR(255),
  "Casasdecimaisquantidade" VARCHAR,
  "Casasdecimaisvalorunitario" VARCHAR,
  "Codigototalizadorparcial" VARCHAR(255),
  "Lote" VARCHAR(255),
  "Lklote" INT,
  "Autoprevsaude" INT,
  "Descespecial" DECIMAL,
  "Turno" INT
);